AjaxJson/Controllers/JsonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AjaxJson.Models;
using System.Linq.Dynamic;
using System.ComponentModel.DataAnnotations;

namespace AjaxJson.Controllers
{
    public class CustomDateRangeAttribute : RangeAttribute
    {
        public CustomDateRangeAttribute() : base(typeof(DateTime), DateTime.Now.AddYears(-150).ToString(), DateTime.Now.AddYears(-18).ToString())
        { }
    }
    public class JsonController : Controller
    {
        // es un true false que indica
        // si se dibujara de nuevo el
        //data table en cada interaccion
        public string draw = "";
        // es la pagina en la que empesara
        public string start = "";
        // es la longitud de la coleccion de datos
        public string length = "";
        // es la columna por la que esta ordenado
        public string sortColumn = "";
        //si es ascendente o descendente
        public string sortColumnDir = "";
        // es si se busca un dato
        public string searchValue = "";
        //pageSize es el numero de registro
        // skip ignorame todos los registro 
        // que esten a la izquierda
        // record total cuantos registros hay
        public int pageSize, skip, recordsTotal;
        // GET: Json
        public ActionResult Index()
        {

                return View();
        }
        [HttpPost]
        public JsonResult Eliminar(int id)
        {
            bool resultado = true;
            if (id >0)
            {
                try
                {
                    Persona persona = new Persona();
                    using (AjaxJsonEntities db = new AjaxJsonEntities())
                    {
                        persona = (from d in db.Personas
                                   select d).Where(d => d.id == id).FirstOrDefault();
                        if (persona != null)
                        {
                            db.Personas.Remove(persona);
                            db.SaveChanges();
                        }
                    }
                }
                catch(Exception ex)
                {
                    resultado = false;
                }
                
            }
            
            
            return Json(new { resultado = resultado }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult Guardar(Persona opersona)
        {
            bool respuesta = true;
            try
            {
                if (opersona.id == 0)
                {
                    using (AjaxJsonEntities db = new AjaxJsonEntities())
                    {
                        db.Personas.Add(opersona);
                        db.SaveChanges();
                    }
                }
                else
                {
                    using (AjaxJsonEntities db = new AjaxJsonEntities())
                    {
                        Persona tempPersona =
                         (from d in db.Personas
                          select d).Where(d => d.id == opersona.id).FirstOrDefault();
                        tempPersona.Nombre = opersona.Nombre;
                        tempPersona.Edad = opersona.Edad;
                        db.Entry(tempPersona).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                }

            }
            catch (Exception ex)
            {
                respuesta = false;
            }
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ObtenerPersona(int id)
        {
            Persona persona = new Persona();
            using (AjaxJsonEntities db = new AjaxJsonEntities())
            {
                persona = (from d in db.Personas
                       select d).Where(d => d.id == id).FirstOrDefault();
            }
                return Json( persona, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult ObtenerPersonas()
        {
            List<Persona> lst = new List<Persona>();
            //logistica datatable
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
            var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();


            pageSize = length != null ? Convert.ToInt32(length) : 0;
            skip = start != null ? Convert.ToInt32(start) : 0;
            recordsTotal = 0;
            using (AjaxJsonEntities db = new AjaxJsonEntities())
            {
                IQueryable<Persona> query = (from d in db.Personas
                                    select d);
                if(searchValue != "")
                {
                    query = query.Where(x => x.Nombre.Contains(searchValue));
                }
               
                //Sorting    
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                {
                    query = query.OrderBy(sortColumn + " " + sortColumnDir);
                }
                recordsTotal = query.Count();
                lst = query.Skip(skip).Take(pageSize).ToList();
                
            }
            return Json(
                new {draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = lst }
                 );
        }
    }
}

AjaxJson/Views/Json/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="row m-4">
    <div class="col-sm-12">
        <div class="card-header">
            Emjemplo Crud MVC Datatable jquery
        </div>
        <div class="cad-body">
            <table id="table_id" class="display">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Edad</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Editar</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>

                    <div class="form-group">
                        <label for="textNombre" class="col-form-label">Nombre:</label>
                        <input type="text" class="form-control" id="textNombre">
                    </div>
                    <div class="form-group">
                        <label for="numberEdad" class="col-form-label">Edad:</label>
                        <input type="number" class="form-control" id="numberEdad">
                    </div>
                    <input type="hidden" id="hiddenid">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        var table_id;
        $(document).ready(function () {
           table_id =
            $('#table_id').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": {
                    "url": "@Url.Content("~/Json/ObtenerPersonas")",
                    "type": "POST",
                    "datatype": "json"
                },
                "pageLength": 10,
                "filter": true,
                "responsivePriority": 1,
                "data": null,
                "columns": [
                { "data": "Nombre", "name": "Nombre", "autoWidth": true },
                    { "data": "Edad", "name": "Edad", "autoWidth": true },
                    {
                        "data": "id", "render": function (data) {
                            return "<button class='btn btn-primary btn-sm' onclick='abrirmodal(" + data + ")'> " +
                                "<i class='fas fa-pen'></i></button>" +
                                "<button class='btn btn-danger btn-sm ml-2' onclick='eliminar(" + data + ")'> " +
                                "<i class='fa-solid fa-trash'></i></button>"

                        }

                        //,
                        //"orderable": false,
                        //"searchable": false,
                        //"width": "150px"
                    }
                ],
                dom: 'Bfrtip',
                buttons: [
                    {
                        text: 'Agregar Nuevo',
                        attr: { class: 'btn btn-success btn-sm'},
                        action: function (e, dt, node, config) {
                            abrirmodal(0)
                        }
                    }
                ]


            });

        });
        function abrirmodal($id) {
            if($id != 0)
            {

                $.ajax({
                    url: "@Url.Content("~/Json/ObtenerPersona")" + "?id=" + $id,
                    type: "GET",
                    datatype: "json",
                    contentType: "aplication/json charset-utf-8",
                    success: function (data) {
                        if (data != null) {
                            $("#textNombre").val(data.Nombre);
                            $("#numberEdad").val(data.Edad);
                            $("#hiddenid").val(data.id);
                        }
                    }
                }
                );
            }
            else
            {
                $("#textNombre").val("");
                $("#numberEdad").val("");
                $("#hiddenid").val(0);
            }

            $("#formModal").modal("show");
        };
        function guardar() {
            var $data = {
                opersona: {
                id: parseInt($("#hiddenid").val()),
                Nombre: $("#textNombre").val(),
                Edad: parseInt($("#numberEdad").val())
                }
            }
            console.log($data);
             $.ajax({
                    url: "@Url.Action("Guardar", "Json")",
                 type: "POST",
                    data: JSON.stringify($data),
                 dataType: 'json',
                 contentType: "application/json; charset=utf-8",
                 headers: {
                     'Accept': 'application/json',
                     'Content-Type': 'application/json',
                     'opersona': $data
                 },
                    success: function (data) {
                        if (data.resultado) {
                            table_id.ajax.reload();
                            $("#formModal").modal("hide");
                        }
                        else {
                            alert("no se pudo guardar los cambios");
                        }
                    }
             }
             //    ,
             //    error: function (error) {
             //        console.log(error)
             //},
             //    beforeSend: function () {

             //    }
                );

        }
        function eliminar($id) {
            if (confirm("¿Realmente desea eliminar?")) {
                $.ajax({
                    url: "@Url.Action("Eliminar", "Json")" + "?id=" + $id,
                    type: "POST",
                    dataType: 'json',
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        if (data.resultado) {
                            table_id.ajax.reload();
                        }
                    }
                });
            }
        }
    </script>
}